CREATE TABLE IF NOT EXISTS "authority_articles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"title_bm" text,
	"approval_status" text DEFAULT 'Draft' NOT NULL,
	"approver" text,
	"created_by" text NOT NULL,
	"run_id" text NOT NULL,
	"compliance_check" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"topic" text,
	"target_query" text,
	"body_en" text,
	"body_bm" text,
	"faq_en" text,
	"faq_bm" text,
	"citations" text,
	"aeo_schema" text,
	"target_channels" jsonb,
	"slug" text,
	"description" text,
	"reading_time" text,
	"keywords" jsonb,
	"og_image_url" text,
	"hero_image_url" text,
	"hero_image_alt" text,
	"related_slugs" jsonb,
	"delivered_at" timestamp with time zone,
	"delivered_to" text,
	"pr_url_en" text,
	"pr_url_bm" text,
	"topic_tag" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "briefs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"title_bm" text,
	"approval_status" text DEFAULT 'Draft' NOT NULL,
	"approver" text,
	"created_by" text NOT NULL,
	"run_id" text NOT NULL,
	"compliance_check" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"persona" text,
	"angle" text,
	"promise" text,
	"proof_type" jsonb,
	"funnel_stage" text,
	"body_en" text,
	"body_bm" text,
	"source_insights" text,
	"budget_bucket" text,
	"linked_hypotheses" jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "creative_variants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"title_bm" text,
	"approval_status" text DEFAULT 'Draft' NOT NULL,
	"approver" text,
	"created_by" text NOT NULL,
	"run_id" text NOT NULL,
	"compliance_check" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"script" text,
	"format" text,
	"aspect" text,
	"shotlist_en" text,
	"shotlist_bm" text,
	"thumbnail_brief" text,
	"estimated_cost_myr" real,
	"asset_files" jsonb,
	"image_generation_notes" text,
	"ad_id" text,
	"channels" jsonb,
	"yt_title" text,
	"yt_description" text,
	"yt_tags" jsonb,
	"yt_category" text,
	"yt_video_id" text,
	"meta_primary_text_en" text,
	"meta_primary_text_bm" text,
	"meta_headline_en" text,
	"meta_headline_bm" text,
	"meta_description_en" text,
	"meta_description_bm" text,
	"meta_cta_type" text,
	"meta_targeting_json" text,
	"organic_language" text,
	"organic_caption_en" text,
	"organic_caption_bm" text,
	"organic_hashtags_ig" jsonb,
	"organic_hashtags_fb" jsonb,
	"organic_status" text,
	"organic_scheduled_for" timestamp with time zone,
	"organic_approval_notes" text,
	"pipeline_notes" text,
	"reel_heygen_job_id" text,
	"reel_mp4_url" text,
	"ig_post_id" text,
	"fb_post_id" text,
	"organic_published_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "experiments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"title_bm" text,
	"approval_status" text DEFAULT 'Draft' NOT NULL,
	"approver" text,
	"created_by" text NOT NULL,
	"run_id" text NOT NULL,
	"compliance_check" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"hypothesis" text,
	"factors" text,
	"cells" text,
	"primary_metric" text,
	"daily_budget_myr" real,
	"duration_days" integer,
	"status" text,
	"test_type" text,
	"launch_window" text,
	"readout" text,
	"linked_variants" jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hypotheses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"title_bm" text,
	"approval_status" text DEFAULT 'Draft' NOT NULL,
	"approver" text,
	"created_by" text NOT NULL,
	"run_id" text NOT NULL,
	"compliance_check" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"statement_en" text,
	"statement_bm" text,
	"predicted_effect" text,
	"predicted_range" text,
	"status" text,
	"predictions_history" text,
	"calibration_score" real,
	"domain" jsonb,
	"channel" jsonb,
	"test_experiment" text,
	"discovered_run" text,
	"resolved_run" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "learnings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"title_bm" text,
	"approval_status" text DEFAULT 'Draft' NOT NULL,
	"approver" text,
	"created_by" text NOT NULL,
	"run_id" text NOT NULL,
	"compliance_check" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"claim_en" text,
	"claim_bm" text,
	"confidence" text,
	"half_life_days" integer,
	"last_validated_at" timestamp with time zone,
	"status" text,
	"domain" jsonb,
	"source_hypotheses" jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "performance_reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"title_bm" text,
	"approval_status" text DEFAULT 'Draft' NOT NULL,
	"approver" text,
	"created_by" text NOT NULL,
	"run_id" text NOT NULL,
	"compliance_check" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"window" text,
	"top_creatives" text,
	"fatiguing" text,
	"cost_per_angle" text,
	"decision_memo_en" text,
	"decision_memo_bm" text,
	"self_critique" text,
	"bandit_allocation" text,
	"linked_briefs" jsonb,
	"linked_experiments" jsonb,
	"linked_hypotheses" jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scripts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"title_bm" text,
	"approval_status" text DEFAULT 'Draft' NOT NULL,
	"approver" text,
	"created_by" text NOT NULL,
	"run_id" text NOT NULL,
	"compliance_check" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"brief" text,
	"format" text,
	"funnel_stage" text,
	"proof_refs" jsonb,
	"hook_en" text,
	"hook_bm" text,
	"script_en" text,
	"script_bm" text,
	"duration_sec" integer,
	"cta_en" text,
	"cta_bm" text
);
